name: Build and Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: '🛠️ Build'
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3
      
      - name: 🛠️ Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: 📦 Install dependencies
        uses: bahmutov/npm-install@v1
      
      - name: 🏗️ Build
        run: npm run build
      
      - name: 🧹 Lint with EsLint
        run: npm run lint
